### ISSUE TITLE
Implement add todo functionality

### ISSUE THREAD

**Issue by MRadzynski** [MRadzynski/ToDo-ReactPolandTask#7]
- [x] Create separate view
- [x] Add form
- [x] Create function to add todo
- [x] Update redux store with new todo
